# CircleCI configuration file
version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  hello_from_node:
    executor: node/default
    steps:
      - run: 
          command: node -p "console.log('hello world from circleCI');"
          name: running node js script
      - run:
          command: node -p "console.log(process.env.MY_VALUE)"
          name: trying to read the env value
      - run:
          name: echo
          command: |
            echo "${MY_NAME}"
          

  # Job one with a unique name
  say_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"
  # Job two with a unique name
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"
workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye
      - hello_from_node