version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor:
      name: node/default
      tag: '14.17' # You can specify the Node.js version here
    steps:
      - checkout
      - run:
          command: node main.js
          name: running script
