version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest # Use the latest Node.js image
    steps:
      - checkout
      - run:
          name: Run Node.js Script
          command: node main.js