version: 2.1

jobs:
  my_job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run my tasks
          command: |
            echo "Running scheduled tasks..."

workflows:
  hourly-schedule:
    triggers:
      - schedule:
          cron: "50 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - my_job
